packages:
    - apps/*
    - packages/*
    - docs
allowBuilds:
    esbuild: true
    husky: true
    nx: true
    sharp: false
ignoredBuiltDependencies:
    - sharp
onlyBuiltDependencies:
    - esbuild
    - husky
    - nx
