CREATE TABLE "company"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    "createdOn"  TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "modifiedOn" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "name"       VARCHAR(255) NULL
);

CREATE TABLE "user"
(
    "id"                      BIGINT GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    "createdOn"               TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "modifiedOn"              TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "firstName"               VARCHAR(30) NOT NULL,
    "lastName"                VARCHAR(30) NOT NULL,
    "companyId"               BIGINT NOT NULL,
    "password"                VARCHAR(70) NOT NULL,
    "email"                   VARCHAR(100) NOT NULL,
    "role"                    VARCHAR(5) NOT NULL,
    "permissionLogin"         BOOLEAN DEFAULT TRUE NOT NULL,
    "lastLoginOn"             TIMESTAMPTZ NULL,
    "phone"                   VARCHAR(30) NULL,
    "loginDisabledOn"         TIMESTAMPTZ NULL,
    "passwordResetGuid"       VARCHAR(100) NULL,
    "verifyEmailPin"          INTEGER NULL,
    "verifyEmailPinExpiresOn" TIMESTAMPTZ NULL,
    "accountStatus"           VARCHAR(9) DEFAULT 'view_only' NOT NULL,
    "passwordResetExpiresOn"  TIMESTAMPTZ NULL,
    "onboardingStatus"        VARCHAR(12) DEFAULT 'verify_email' NOT NULL,
    "pendingEmail"            VARCHAR(100) NULL,
    "testAge"                 INT DEFAULT 0 NULL,

    CONSTRAINT "user_email_unique_index" UNIQUE ("email"),
    CONSTRAINT "user_companyId_company_id_fk"
        FOREIGN KEY ("companyId") REFERENCES "company" ("id")
);

-- Indexes
CREATE INDEX "user_companyId_index"
    ON "user" ("companyId");

CREATE INDEX "user_passwordResetGuid_index"
    ON "user" ("passwordResetGuid");

-- Check constraints for ENUM-like functionality
ALTER TABLE "user"
    ADD CONSTRAINT "role_check"
        CHECK ("role" IN ('admin', 'user'));

ALTER TABLE "user"
    ADD CONSTRAINT "accountStatus_check"
        CHECK ("accountStatus" IN ('banned', 'view_only', 'active'));

ALTER TABLE "user"
    ADD CONSTRAINT "onboardingStatus_check"
        CHECK ("onboardingStatus" IN ('verify_email', 'complete'));
