-- Create the ENUM types
CREATE TYPE role_enum AS ENUM ('admin', 'user');
CREATE TYPE account_status_enum AS ENUM ('banned', 'view_only', 'active');
CREATE TYPE onboarding_status_enum AS ENUM ('verify_email', 'complete');

-- Create the company table
CREATE TABLE "company"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdOn"  TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "modifiedOn" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "name"       VARCHAR(255) NULL
);

-- Create the user table with ENUMs for role, accountStatus, and onboardingStatus
CREATE TABLE "user"
(
    "id"                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "createdOn"               TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "modifiedOn"              TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "firstName"               VARCHAR(30) NOT NULL,
    "lastName"                VARCHAR(30) NOT NULL,
    "companyId"               BIGINT NOT NULL,
    "password"                VARCHAR(70) NOT NULL,
    "email"                   VARCHAR(100) NOT NULL,
    "role"                    role_enum NOT NULL,
    "permissionLogin"         BOOLEAN DEFAULT TRUE NOT NULL,
    "lastLoginOn"             TIMESTAMPTZ NULL,
    "phone"                   VARCHAR(30) NULL,
    "loginDisabledOn"         TIMESTAMPTZ NULL,
    "passwordResetGuid"       VARCHAR(100) NULL,
    "verifyEmailPin"          INTEGER NULL,
    "verifyEmailPinExpiresOn" TIMESTAMPTZ NULL,
    "accountStatus"           account_status_enum DEFAULT 'view_only' NOT NULL,
    "passwordResetExpiresOn"  TIMESTAMPTZ NULL,
    "onboardingStatus"        onboarding_status_enum DEFAULT 'verify_email' NOT NULL,
    "pendingEmail"            VARCHAR(100) NULL,
    "testAge"                 INT DEFAULT 0 NULL,

    CONSTRAINT "user_email_unique_index" UNIQUE ("email"),
    CONSTRAINT "user_companyId_company_id_fk"
        FOREIGN KEY ("companyId") REFERENCES "company" ("id")
);

-- Indexes
CREATE INDEX "user_companyId_index"
    ON "user" ("companyId");

CREATE INDEX "user_passwordResetGuid_index"
    ON "user" ("passwordResetGuid");

-- Create some test data
INSERT INTO public.company (id, "createdOn", "modifiedOn", name)
VALUES (1, '2024-10-13 17:35:45.989731 +00:00', '2024-10-13 17:35:45.989731 +00:00', 'redsky');


INSERT INTO public."user" ("createdOn", "modifiedOn", "firstName", "lastName", "companyId", password, email, role,
                           "permissionLogin", "lastLoginOn", phone, "loginDisabledOn", "passwordResetGuid",
                           "verifyEmailPin", "verifyEmailPinExpiresOn", "accountStatus", "passwordResetExpiresOn",
                           "onboardingStatus", "pendingEmail", "testAge")
VALUES ('2024-10-13 17:57:28.180898 +00:00', '2024-10-13 17:57:28.180898 +00:00', 'Tanner', 'Burton', 1, 'asdfa',
        'tanner@plvr.com', 'user', true, null, null, null, null, null, null, 'view_only', null, 'verify_email',
        null, 0);